#define SIMULATION_CANVA_X      200
#define SIMULATION_CANVA_Y      160
#define SIMULATION_CANVA_WIDTH  1280
#define SIMULATION_CANVA_HEIGHT 800
#define SIMULATION_CELL         80
#define SIMULATION_CELL_X       SIMULATION_CELL + (SIMULATION_CANVA_X)
#define SIMULATION_CELL_Y       SIMULATION_CELL + (SIMULATION_CANVA_Y)

#define SIMULATION_BLUE         7991807
#define SIMULATION_LIGHTGRAY    -926365441
#define SIMULATION_GRAY         -2105376001

const unsigned short simulation_rectangles_size = 21;
const int simulation_rectangles[][5] = {
    /* GUI on the right */
        { (SIMULATION_CANVA_X) + (SIMULATION_CANVA_WIDTH) + (SIMULATION_CELL), SIMULATION_CANVA_Y, (SIMULATION_CELL), (SIMULATION_CELL), SIMULATION_BLUE },
    /* Cells */
    // X = 0 (first column)
        { (0*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (0*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
    // X = 1 (second column)
        { (1*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },
        { (1*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2, SIMULATION_GRAY },

};