#define SIMULATION_CANVA_X      200
#define SIMULATION_CANVA_Y      160
#define SIMULATION_CANVA_WIDTH  1280
#define SIMULATION_CANVA_HEIGHT 800
#define SIMULATION_CELL         80
#define SIMULATION_CELL_X       SIMULATION_CELL + (SIMULATION_CANVA_X)
#define SIMULATION_CELL_Y       SIMULATION_CELL + (SIMULATION_CANVA_Y)
#define SIMULATION_CIRCLE       40

#define SIMULATION_BLUE         7991807
#define SIMULATION_LIGHTGRAY    -926365441
#define SIMULATION_GRAY         -2105376001
#define SIMULATION_RED          -433506305
#define SIMULATION_GREEN        14954751

const unsigned char simulation_arrows_directions[] = {
    0,  // no arrows directions
    118,  // arrow on the left
    119,  // arrow on the right
    120,  // arrow on the bottom
    121,  // arrow on the top
};
const unsigned short simulation_arrows_directions_size = sizeof(simulation_arrows_directions) / sizeof(simulation_arrows_directions[0]);

const unsigned short simulation_rectangles[][4] = {
    /* GUI on the right */
        { (SIMULATION_CANVA_X) + (SIMULATION_CANVA_WIDTH) + (SIMULATION_CELL), SIMULATION_CANVA_Y + (2 * (SIMULATION_CELL)), (SIMULATION_CELL), (SIMULATION_CELL) },
    /* Cells */
    // X = 0 (first column)
        { (0*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (0*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 1 (second column)
        { (1*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (1*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 2 (third column)
        { (2*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (2*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 3 (forth column)
        { (3*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (3*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 4 (fifth column)
        { (4*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (4*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 5 (sixth column)
        { (5*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (5*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 6 (seventh column)
        { (6*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (6*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 7 (eight column)
        { (7*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (7*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 8 (nineth column)
        { (8*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (8*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 9 (tenth column)
        { (9*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (9*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 10 (eleventh column)
        { (10*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (10*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 11 (twelfth column)
        { (11*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (11*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 12 (thirtennth column)
        { (12*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (12*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 13 (fourteenth column)
        { (13*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (13*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 14 (fifteenth column)
        { (14*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (14*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    // X = 15 (sixtennth column)
        { (15*SIMULATION_CELL_X)+1, (0*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (1*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (2*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (3*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (4*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (5*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (6*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (7*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (8*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
        { (15*SIMULATION_CELL_X)+1, (9*SIMULATION_CELL_Y)+1, (SIMULATION_CELL)-2, (SIMULATION_CELL)-2 },
    /* GUI on the right */
        { (SIMULATION_CANVA_X) + (SIMULATION_CANVA_WIDTH) + (SIMULATION_CELL), SIMULATION_CANVA_Y, (SIMULATION_CELL), (SIMULATION_CELL) }, // BLUE WALL BUTTON
        { (SIMULATION_CANVA_X) + (SIMULATION_CANVA_WIDTH) + (SIMULATION_CELL), SIMULATION_CANVA_Y + (4*(SIMULATION_CELL)), (SIMULATION_CELL), (SIMULATION_CELL) }, // GREEN PATH BUTTON
        { (SIMULATION_CANVA_X) + (SIMULATION_CANVA_WIDTH) + (SIMULATION_CELL), SIMULATION_CANVA_Y + (6*(SIMULATION_CELL)), (SIMULATION_CELL), (SIMULATION_CELL) }, // RED SPAWNING BUTTON

};
const unsigned short simulation_rectangles_size = sizeof(simulation_rectangles) / sizeof(simulation_rectangles[0]);

